### ISSUE TITLE
Numpy Concatation Error on S2COGREADER.part

### ISSUE THREAD

**Issue by jameshgrn** [cogeotiff/rio-tiler-pds#11] opened 2020-08-30 21:23 UTC
Hey all, I am trying to use S2COGREADER to read part of a raster according to a bbox..
here is my geojson courtesy of geojson.io
```
geojson = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              35.013427734375,
              2.0869407308811065
            ],
            [
              37.46337890624999,
              2.0869407308811065
            ],
            [
              37.46337890624999,
              4.850154078505659
            ],
            [
              35.013427734375,
              4.850154078505659
            ],
            [
              35.013427734375,
              2.0869407308811065
            ]
          ]
        ]
      }
    }
  ]
}
```

I then use featureBounds to get the bbox and pass it to the reader with a band expression:
```
geom = geojson["features"][0]["geometry"]
with S2COGReader("S2A_29RKH_20200219_0_L2A") as sen:
    data = sen.part(bbox=featureBounds(geom), expression="(B03-B11)/(B03+B11)")
```

I get this error

`ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 618 and the array at index 1 has size 555`

I have tried different geometries and different ID numbers. Any help?

**Comment by kylebarron** [comment] 2020-08-30 23:13
Maybe related to the fact that Band 3 has 10m resolution and Band 11 has 20m resolution? Try with B03 and B04?

**Comment by jameshgrn** [comment] 2020-08-30 23:30
Kyle, cheers. That seemed to be the problem.

**Comment by kylebarron** [comment] 2020-08-30 23:31
I'd argue this is still a bug, or at a minimum there should be a better error message. What do you think @vincentsarago?

**Comment by vincentsarago** [comment] 2020-08-30 23:37
It's a tricky problem and will only happens if the bbox in the raw resolution result in a array > 1024px (I think) 
The problem is that each band can have different resolution and we can't really now it in advance 

To fix this you can either limit the 'max-size' to a smaller value or to fix the width and height. 

We could maybe resolve this in the 'multi_array' function by resembling each array to the same size!

**Comment by kylebarron** [comment] 2020-08-30 23:48
I'm surprised the arrays (size 618 and 555) aren't a factor of two

**Comment by jameshgrn** [comment] 2020-08-30 23:51
I reopened the issue, let me know if you want me to close it. I'll do what @vincentsarago suggested and report back

**Comment by vincentsarago** [comment] 2020-08-30 23:53
Why it should be factor of two @kylebarron?
This is for the 'part' method (would be the same for preview if one file is smaller than 1024px).

**Comment by kylebarron** [comment] 2020-08-31 02:01
I don't know the internals of `part` well enough but I just assumed a factor of two because the resolutions are a factor of two apart

**Comment by vincentsarago** [comment] 2023-04-11 15:23
This is fixed in rio-tiler now.

**Closed by vincentsarago** 2023-04-11 15:23 UTC
